name: Code formatter and linter

on:
  push:
    branches: ["master", "main", "rewrite"]

permissions:
  contents: write

jobs:

  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff pyright pygame python-dotenv
      - name: Format with isort and black
        run: |
          isort .
          black .
      - name: Linting with ruff
        run: |
          ruff .
      - name: Type checking with pyright
        run: |
          pyright .
